feat: add Stone - link to site and code
felipefialho/frontend-challenges pull request #137
Opened 2023-04-18 23:39 UTC by Fernanda-Kipper

# :warning: Just open-source challenges! Please! :warning:

2023-04-19 12:14 UTC, felipefialho requested changes

2023-04-19 12:14 UTC, felipefialho commented on readme.md
> +| pt   | :brazil: [Stone](https://www.stone.com.br/)                                   | React, Typescript, Styled Components, Testes unitários | [Code →](https://github.com/stone-payments/template-d
@Fernanda-Kipper, muito obrigado pela contribuição, pode colocar em ordem alfabética? 😄

2023-04-20 10:23 UTC, Fernanda-Kipper commented on readme.md
> +| pt   | :brazil: [Stone](https://www.stone.com.br/)                                   | React, Typescript, Styled Components, Testes unitários | [Code →](https://github.com/stone-payments/template-d
Claro! Vou ajustar aqui, desculpe :)

2023-04-20 12:27 UTC, felipefialho commented on readme.md
> +| pt   | :brazil: [Stone](https://www.stone.com.br/)                                   | React, Typescript, Styled Components, Testes unitários | [Code →](https://github.com/stone-payments/template-d
Magina <3

2023-04-20 12:27 UTC, felipefialho approved these changes

2023-04-20 12:27 UTC, felipefialho commented
Tks @Fernanda-Kipper 😄

2023-04-20 12:27 UTC, merged